import { Project, ProjectManager } from './types';

export const HARDCODED_USERS: ProjectManager[] = [
  {
    id: 'pm1',
    name: 'Sarah Chen',
    email: 'sarah@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  },
  {
    id: 'pm2',
    name: 'Alex Rivera',
    email: 'alex@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  },
  {
    id: 'pm3',
    name: 'Jordan Kim',
    email: 'jordan@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
  },
  {
    id: 'dev1',
    name: 'Marcus Johnson',
    email: 'marcus@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
  },
  {
    id: 'dev2',
    name: 'Elena Petrov',
    email: 'elena@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
  },
  {
    id: 'dev3',
    name: 'Aisha Williams',
    email: 'aisha@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
  },
];

export const SAMPLE_PROJECTS: Project[] = [
  {
    id: 'proj1',
    name: 'Brand Redesign 2024',
    workspace: 'logo',
    status: 'in-progress',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // 5 days
    priority: 'high',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop',
    pm: 'pm1',
    developer: 'dev1',
    labels: [
      { id: 'label1', name: 'Branding', color: '#3B82F6' },
      { id: 'label2', name: 'Urgent', color: '#EF4444' },
    ],
    description: 'Complete redesign of our brand identity including logo, colors, and typography.',
    checklist: [
      { id: 'check1', title: 'Mood board creation', completed: true },
      { id: 'check2', title: 'Color palette selection', completed: true },
      { id: 'check3', title: 'Logo concepts', completed: false },
    ],
    comments: [
      {
        id: 'cmt1',
        userId: 'pm1',
        content: 'Let\'s aim for a modern, minimalist approach.',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
    ],
    attachments: [],
    activityLog: [
      {
        id: 'act1',
        userId: 'pm1',
        action: 'Created project',
        timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'proj2',
    name: 'Mobile App Interface',
    workspace: 'web-design',
    status: 'in-progress',
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    priority: 'high',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=500&h=300&fit=crop',
    pm: 'pm1',
    developer: 'dev2',
    labels: [
      { id: 'label3', name: 'Design', color: '#A855F7' },
      { id: 'label4', name: 'Mobile', color: '#06B6D4' },
    ],
    description: 'Design the complete mobile app interface for iOS and Android.',
    checklist: [
      { id: 'check4', title: 'Wireframes', completed: true },
      { id: 'check5', title: 'Visual design', completed: false },
      { id: 'check6', title: 'Prototype', completed: false },
    ],
    comments: [],
    attachments: [],
    activityLog: [],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'proj3',
    name: 'API Development',
    workspace: 'web-development',
    status: 'in-progress',
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // Overdue
    priority: 'critical',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    pm: 'pm2',
    developer: 'dev1',
    labels: [
      { id: 'label5', name: 'Backend', color: '#EF4444' },
      { id: 'label6', name: 'Overdue', color: '#DC2626' },
    ],
    description: 'Develop REST API endpoints for the new platform.',
    checklist: [
      { id: 'check7', title: 'Authentication', completed: true },
      { id: 'check8', title: 'User endpoints', completed: true },
      { id: 'check9', title: 'Payment integration', completed: false },
    ],
    comments: [
      {
        id: 'cmt2',
        userId: 'dev1',
        content: 'Payment integration is more complex than expected, need more time.',
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
    ],
    attachments: [],
    activityLog: [],
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'proj4',
    name: 'Product Documentation',
    workspace: 'content',
    status: 'Completed',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    priority: 'medium',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&h=300&fit=crop',
    pm: 'pm3',
    developer: 'dev3',
    labels: [
      { id: 'label7', name: 'Documentation', color: '#22C55E' },
    ],
    description: 'Write comprehensive product documentation and user guides.',
    checklist: [
      { id: 'check10', title: 'Getting started guide', completed: true },
      { id: 'check11', title: 'API documentation', completed: false },
      { id: 'check12', title: 'Video tutorials', completed: false },
    ],
    comments: [],
    attachments: [],
    activityLog: [],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'proj5',
    name: 'Launch Campaign',
    workspace: 'content',
    status: 'Completed',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // Completed
    priority: 'high',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
    pm: 'pm1',
    developer: null,
    labels: [
      { id: 'label8', name: 'Marketing', color: '#F97316' },
      { id: 'label9', name: 'Completed', color: '#22C55E' },
    ],
    description: 'Execute the product launch marketing campaign across all channels.',
    checklist: [
      { id: 'check13', title: 'Email campaign', completed: true },
      { id: 'check14', title: 'Social media posts', completed: true },
      { id: 'check15', title: 'Press release', completed: true },
    ],
    comments: [],
    attachments: [],
    activityLog: [],
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'proj6',
    name: 'User Testing Phase',
    workspace: 'web-design',
    status: 'Revisons',
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    priority: 'medium',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500&h=300&fit=crop',
    pm: 'pm2',
    developer: 'dev2',
    labels: [
      { id: 'label10', name: 'Testing', color: '#06B6D4' },
      { id: 'label11', name: 'QA', color: '#22C55E' },
    ],
    description: 'Conduct user testing sessions and gather feedback.',
    checklist: [
      { id: 'check16', title: 'Recruit participants', completed: true },
      { id: 'check17', title: 'Run sessions', completed: true },
      { id: 'check18', title: 'Analyze feedback', completed: false },
    ],
    comments: [],
    attachments: [],
    activityLog: [],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'proj7',
    name: 'Analytics Dashboard',
    workspace: 'web-development',
    status: 'Completed',
    dueDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    priority: 'medium',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=300&fit=crop',
    pm: 'pm3',
    developer: 'dev3',
    labels: [
      { id: 'label12', name: 'Analytics', color: '#3B82F6' },
    ],
    description: 'Build an analytics dashboard to track key metrics.',
    checklist: [
      { id: 'check19', title: 'Database schema', completed: true },
      { id: 'check20', title: 'API endpoints', completed: false },
      { id: 'check21', title: 'Frontend components', completed: false },
    ],
    comments: [],
    attachments: [],
    activityLog: [],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'proj8',
    name: 'Database Optimization',
    workspace: 'web-development',
    status: 'Todo',
    dueDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    priority: 'low',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    pm: 'pm1',
    developer: 'dev1',
    labels: [
      { id: 'label13', name: 'Backend', color: '#EF4444' },
    ],
    description: 'Optimize database queries and indexing.',
    checklist: [
      { id: 'check22', title: 'Query analysis', completed: true },
      { id: 'check23', title: 'Index optimization', completed: false },
    ],
    comments: [],
    attachments: [],
    activityLog: [],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'proj9',
    name: 'Security Audit',
    workspace: 'web-development',
    status: 'Revisons',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    priority: 'critical',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500&h=300&fit=crop',
    pm: 'pm2',
    developer: null,
    labels: [
      { id: 'label14', name: 'Security', color: '#DC2626' },
    ],
    description: 'Conduct comprehensive security audit and fix vulnerabilities.',
    checklist: [
      { id: 'check24', title: 'Vulnerability scan', completed: true },
      { id: 'check25', title: 'Fix critical issues', completed: false },
      { id: 'check26', title: 'Penetration testing', completed: false },
    ],
    comments: [],
    attachments: [],
    activityLog: [],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'proj10',
    name: 'Frontend Performance',
    workspace: 'web-design',
    status: 'Todo',
    dueDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
    priority: 'high',
    image: 'https://images.unsplash.com/photo-1560707303-4e980ce876ad?w=500&h=300&fit=crop',
    pm: 'pm3',
    developer: 'dev2',
    labels: [
      { id: 'label15', name: 'Frontend', color: '#A855F7' },
    ],
    description: 'Optimize frontend performance and implement caching strategies.',
    checklist: [
      { id: 'check27', title: 'Lighthouse audit', completed: true },
      { id: 'check28', title: 'Bundle optimization', completed: false },
      { id: 'check29', title: 'Implement caching', completed: false },
    ],
    comments: [],
    attachments: [],
    activityLog: [],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
];
